name: "HVAC MPC Controller"
version: "0.0.1"
slug: "hvac_mpc_controller"
description: "Model Predictive Control HVAC system with CO2 and ventilation management"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ports:
  8000/tcp: 8000
map:
  - config:rw
options:
  # Sensor selection
  co2_sensor: "sensor.living_room_co2"
  temperature_sensor: "sensor.living_room_temperature"
  weather_entity: "weather.home"
  
  # Controller settings
  horizon_hours: 24
  co2_weight: 1.0
  energy_weight: 1.0
  comfort_weight: 1.0
  co2_target_ppm: 800
  temp_target_c: 22.0
  step_size_hours: 0.25
  optimization_method: "SLSQP"
  max_iterations: 500
  electricity_cost_per_kwh: 0.15
  
  # Building settings
  room_volume_m3: 100.0
  outdoor_co2_ppm: 400.0
  heat_capacity: 1000000.0
  
  # Server settings
  host: "0.0.0.0"
  port: 8000
  log_level: "info"
webui: http://[HOST]:[PORT:8000]

schema:
  co2_sensor: str
  temperature_sensor: str
  weather_entity: str
  horizon_hours: int
  co2_weight: float
  energy_weight: float
  comfort_weight: float
  co2_target_ppm: int
  temp_target_c: float
  step_size_hours: float
  optimization_method: str
  max_iterations: int
  electricity_cost_per_kwh: float
  room_volume_m3: float
  outdoor_co2_ppm: float
  heat_capacity: float
  host: str
  port: int
  log_level: str

ingress: true
ingress_port: 8000 