name: "HVAC MPC Controller"
version: "0.0.1"
slug: "hvac_mpc_controller"
description: "Model Predictive Control HVAC system with CO2 and ventilation management"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ports:
  8000/tcp: 8000
map:
  - config:rw
options:

  # Server settings
  host: "0.0.0.0"
  port: 8000
  log_level: "info"

schema:
  host: str
  port: int
  log_level: str

ingress: true
ingress_port: 8000 